### PR TITLE
Add additional commands and RJ-12 interface description

### PR DESCRIPTION
**Pull request by danieltwagner**
My Fully Jarvis has a Jiecang JCB36N2CA controller with additional RJ-12 connector. This PR adds a description for that physical interface.

I also discovered additional commands and responses which are included in this PR.

### CODE REVIEW

**Comment by phord** [comment]
Nice work.  Thanks for contributing.  

I recently refactored the protocol code into separate modules.  Have you added these commands to your code?  

I noticed my JCB35N2 also has the RJ-12 interface, but I never plugged anything into it.  

I have seen other desks that have a 2nd port for "ganging" or "chaining" desks.  That is, when one desk moves, they all move.  I wonder if this was in their plan for this port, too.

**Comment by danieltwagner** [comment]
I hadn't, partially because when I checked it out a few weeks ago it didn't translate particularly nicely into platformio (and I don't enjoy the Arduino IDE), so I put together a quick thing to dump the serial lines and talk to the controller. I see you've made a number of changes since and so will take a look again; I'm glad to see this project is still getting love after its satisfied the initial requirement :)

**Comment by phord** [comment]
I starting adding your new finds to the code, but I also split the commands into "handset" and "controller" ones.  And that didn't go as nicely.  Maybe I'll try again later.

I also tried to send some commands, but I don't have a level-shifter on my board, and I don't think I'm able to send any data reliably.  

But I wanted to experiment with the commands.  For instance, the "Move up" command seems suspect to me.  Why would it move up "one unit" only?  Does a continuous stream of them cause the desk to move continuously? Seems like it should take a "distance" or "position" argument.  Maybe I'll experiment more later.

Google Home has messed up my voice integration, so I don't really use it anymore.  It's a just a hobby code project, now.  I see someone has made a small business selling HomeAssistant add-on boards derived from my code.  Good for him.

**Comment by danieltwagner** [comment]
Interesting, I also don't have a level shifter. I'm having my ESP8266 pull down the line and it works fine. I'm doing something like
```
void send_msg(std::vector<byte> content, byte sender = 0xF1) {
  hsSerial.write(sender);
  hsSerial.write(sender);

  byte sum = 0;
  for(int c : content) {
    hsSerial.write(c);
    sum += c;
  }
  hsSerial.write(sum);
  hsSerial.write(0x7E);
}

void setup() {
  hsSerial.begin(9600);
  pinMode(RJ45_HTX, OUTPUT);
  send_msg({0x01, 0x00});
  delay(200);
  send_msg({0x01, 0x00});
}
```
and that works nicely.

Also, you're right to be suspicious of "one step". It's the same behaviour that the up/down keys have: a brief step moves it one small amount, pressing continuously (or sending repeatedly, for me every 200ms seems to work fine; I copied that from the frequency the desk sends position updates and didn't test other intervals) makes the desk move continuously until you stop pressing/sending the command.

I found that it will still move when supplying a parameter but the parameter doesn't impact the distance. I didn't dig too much trying to supply two parameters and so on, so there may still be a way to get more precise control.

**Comment by phord** [comment]
Ah, thanks.  That's good to know.  I'm probably doing something wrong on my code, then.  I didn't try very hard yet.  I added a packet encoder and tried to send the RESET command to my handset. I expected it to show RESET on the display, but it didn't react at all.  

Lots of things could go wrong.  My (untested) packet encoder could be bad.  Or my serial config -- previously I didn't configure a `TX` pin at all.  Next step is to get the logic analyzer out and have a look, but I had other things to do for now.

**Pull request merged**
